pycoins/api/urls.py
from django.urls import path, include

from pycoins.api.endpoints import alert, user


urlpatterns = [
    path('auth/', include('rest_auth.urls')),
    path('auth/registration/', include('rest_auth.registration.urls')),

    path(
        'users/',
        user.UserList.as_view(),
        name='user-list',
    ),
    path(
        'users/<int:pk>/',
        user.UserDetail.as_view(),
        name='user-detail',
    ),

    path(
        'users/<int:user_pk>/alerts/',
        alert.AlertList.as_view(),
        name='alert-list',
    ),
    path(
        'users/<int:user_pk>/alerts/<int:pk>/',
        alert.AlertDetail.as_view(),
        name='alert-detail',
    ),
]

pycoins/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework_swagger.views import get_swagger_view

from pycoins.views import account, alert, generic


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v{}/'.format(settings.API_VERSION), include(("pycoins.api.urls", "api"), namespace='api')),


    url(r'^$',
        TemplateView.as_view(template_name="home.html"),
        name='home'),

    # Signup
    url(r'^signup/$',
        TemplateView.as_view(template_name="user/signup.html"),
        name='signup'),

    # Login/out
    url(r'^login/$',
        TemplateView.as_view(template_name="user/login.html"),
        name='login'),

    # Password
    url(r'^password-reset/$',
        TemplateView.as_view(template_name="user/password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="user/password_reset_confirm.html"),
        name='password_reset_confirm'),

    # Current user data
    url(r'^user-details/$',
        generic.RestrictedTemplateView.as_view(template_name="user/user_details.html"),
        name='user-details'),

    # Auto-generated API documentation
    url(r'^docs/$', get_swagger_view(title='API Docs'), name='api_docs'),

    # Alerts
    url(r'^alerts/$',
        alert.AlertListView.as_view(template_name="alert/list.html"),
        name='user-alerts'),

    url(r'^alerts/create/$',
        alert.AlertView.as_view(),
        name='user-alert-create'),

    url(r'^alerts/(?P<pk>\d+)/$',
        alert.AlertView.as_view(),
        name='user-alert-change'),

    url(r'^account/', include('allauth.urls')),

    url(r'^account-confirm-email/(?P<key>[-:\w]+)/$',
        account.confirm_email,
        name='account_confirm_email'),
]

pycoins/admin/models.py
from django.contrib import admin
from django.urls import reverse
from django.utils.safestring import mark_safe

from pycoins.models import Alert, Symbol


class AlertAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'coin_admin', 'currency_admin', 'user_admin',
                    'trigger_type', 'amount', 'evolution', 'evolution_period', 'activated')
    list_filter = ('coin', 'currency', 'trigger_type', 'activated')
    raw_id_fields = ('user',)

    def get_queryset(self, request):
        return (super(AlertAdmin, self)
                .get_queryset(request)
                .select_related('coin', 'currency')
                .prefetch_related('user'))

    def coin_admin(self, obj):
        return mark_safe('<a href="{}">{}</a>'.format(
            reverse('admin:pycoins_symbol_change', kwargs={'object_id': obj.coin_id}),
            obj.coin))

    def currency_admin(self, obj):
        return mark_safe('<a href="{}">{}</a>'.format(
            reverse('admin:pycoins_symbol_change', kwargs={'object_id': obj.currency_id}),
            obj.currency))

    def user_admin(self, obj):
        return mark_safe('<a href="{}">{}</a>'.format(
            reverse('admin:auth_user_change', kwargs={'object_id': obj.user_id}),
            obj.user.username))


class SymbolAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'type')
    list_filter = ('type',)


admin.site.register(Alert, AlertAdmin)
admin.site.register(Symbol, SymbolAdmin)

pycoins/models/alert.py
from datetime import timedelta

from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from extended_choices import Choices
from rest_framework.compat import MinValueValidator, MaxValueValidator
from rest_framework.exceptions import ValidationError

from pycoins.models.symbol import Symbol


class AlertManager(models.Manager):
    def bulk_create(self, objects, *args, **kwargs):
        for obj in objects:
            obj.validate(raise_errors=True)

        return super(AlertManager, self).bulk_create(objects, *args, **kwargs)


class Alert(models.Model):
    TRIGGER_TYPE_CHOICES = Choices(
        ('LOWER', 1, 'Lower than'),
        ('GREATER', 2, 'Greater than'),
        ('EVOLUTION', 3, 'Evolution'),
    )

    coin = models.ForeignKey('Symbol', null=False, blank=False, db_index=True,
                             on_delete=models.PROTECT, limit_choices_to={'type': Symbol.TYPE_CHOICES.COIN},
                             related_name='coin_alerts')  # the related name is meaningless in our case,
                                                          # but Django needs to be indulged here
    currency = models.ForeignKey('Symbol', null=False, blank=False, db_index=True,
                                 on_delete=models.PROTECT, limit_choices_to={'type': Symbol.TYPE_CHOICES.CURRENCY},
                                 related_name='currency_alerts')  # the related name is meaningless in our case,
                                                                  # but Django needs to be indulged here


    user = models.ForeignKey('auth.User', null=False, blank=False, db_index=True,
                             related_name='alerts', on_delete=models.CASCADE)

    trigger_type = models.PositiveSmallIntegerField(choices=TRIGGER_TYPE_CHOICES, null=False, blank=False)

    # For FIXED trigger types
    amount = models.FloatField(null=True, blank=True, validators=[MinValueValidator(0)])

    # For EVOLUTION trigger type
    evolution = models.FloatField(null=True, blank=True, validators=[MinValueValidator(0)])
    evolution_period = models.DurationField(null=True, blank=True, validators=[MaxValueValidator(timedelta(days=5*365))])

    # Alerting settings
    last_sent = models.DateTimeField(null=True, blank=True)
    message_interval = models.DurationField(null=True, blank=True)
    activated = models.BooleanField(null=True, blank=True, db_index=True)

    objects = AlertManager()

    def __str__(self):
        if self.trigger_type == self.TRIGGER_TYPE_CHOICES.EVOLUTION:
            return "{}'s value varies by {}% over a period of {}".format(self.coin.name,
                                                                         self.evolution,
                                                                         self.evolution_period)

        return "{}'s value is {} {}{}".format(self.coin.name,
                                              self.TRIGGER_TYPE_CHOICES.for_value(self.trigger_type).display.lower(),
                                              self.amount,
                                              self.currency.symbol)

    def validate(self, raise_errors=False):
        errors = []

        if self.trigger_type == self.TRIGGER_TYPE_CHOICES.EVOLUTION:
            if not self.evolution:
                errors.append('`evolution` parameter is required for evolution alerts.')

            if not self.evolution_period:
                errors.append('`evolution_period` parameter is required for evolution alerts.')

            self.amount = None

        else:
            if self.amount is None:
                errors.append('`amount` parameter is required for fixed alerts.')

            self.evolution = None
            self.evolution_period = None

        if errors and raise_errors:
            raise ValidationError('\n'.join(errors))

        return errors

    def save(self, *args, **kwargs):
        self.validate(raise_errors=True)
        self.last_sent = None
        return super(Alert, self).save(*args, **kwargs)

    def notify(self):
        if self.last_sent and not self.message_interval:
            # We have already notified the user once and alert is not set to repeat
            return

        if (self.last_sent
            and self.message_interval
            and timezone.now() - self.message_interval < self.last_sent):
            # The user has already been notified within the configured interval
            return

        send_mail('PyCoin Alert',
                  '{}'.format(self),
                  settings.DEFAULT_FROM_EMAIL,
                  [self.user.email])

        self.update_last_sent()

    def update_last_sent(self):
        # Bypass the save method (it resets the 'last_sent' field)
        self.__class__.objects.filter(pk=self.pk).update(last_sent=timezone.now())

pycoins/models/rate.py
from django.db import models

from pycoins.models.symbol import Symbol


class Rate(models.Model):
    coin = models.ForeignKey('Symbol', null=False, blank=False, db_index=True,
                             on_delete=models.PROTECT, limit_choices_to={'type': Symbol.TYPE_CHOICES.COIN},
                             related_name='coin_rates')

    currency = models.ForeignKey('Symbol', null=False, blank=False, db_index=True,
                                 on_delete=models.PROTECT, limit_choices_to={'type': Symbol.TYPE_CHOICES.CURRENCY},
                                 related_name='currency_rates')

    value = models.FloatField(null=False, blank=False)
    time = models.DateTimeField(null=False, blank=False)

pycoins/models/symbol.py
from django.db import models
from extended_choices import Choices


class SymbolQueryset(models.QuerySet):
    def coins(self):
        return self.filter(type=self.model.TYPE_CHOICES.COIN)

    def currencies(self):
        return self.filter(type=self.model.TYPE_CHOICES.CURRENCY)


class SymbolManager(models.Manager):
    def get_queryset(self):
        return SymbolQueryset(self.model)

    def coins(self):
        return self.get_queryset().coins()

    def currencies(self):
        return self.get_queryset().currencies()


class Symbol(models.Model):
    TYPE_CHOICES = Choices(
        ('COIN', 1, 'Coin'),
        ('CURRENCY', 2, 'Currency'),
    )

    name = models.CharField(max_length=50, null=False, blank=False)
    code = models.CharField(max_length=5, null=False, blank=False)
    symbol = models.CharField(max_length=5, null=False, blank=False)

    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, null=False, blank=False)

    objects = SymbolManager()

    def __str__(self):
        return '{} ({}/{})'.format(self.name, self.symbol, self.code)

pycoins/views/account.py
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.utils.http import urlencode
from rest_auth.registration.views import VerifyEmailView


class EmailConfirmationView(VerifyEmailView):
    allowed_methods = ('GET', 'POST', 'OPTIONS', 'HEAD')

    def get(self, request, *args, **kwargs):
        request.data['key'] = self.kwargs['key']
        response = super(EmailConfirmationView, self).post(request, *args, **kwargs)

        query = {}
        if response.status_code == 200:
            query['info'] = "Your email has been confirmed."
        else:
            query['info'] = response.content['detail']

        return HttpResponseRedirect("{}?{}".format(reverse('login'), urlencode(query)))


confirm_email = EmailConfirmationView.as_view()

pycoins/views/alert.py
import json

from rest_framework.reverse import reverse

from pycoins.models import Alert, Symbol
from .generic import RestrictedTemplateView


class BaseAlertView(RestrictedTemplateView):
    def get_context_data(self, **kwargs):
        context = super(BaseAlertView, self).get_context_data(**kwargs)

        context['frontend_app_context'] = json.dumps(
            {
                'alertTriggerTypes': dict(Alert.TRIGGER_TYPE_CHOICES),
                'symbolTypes': dict(Symbol.TYPE_CHOICES),
            }
        )

        context['constants'] = {
            'alert_trigger_types': Alert.TRIGGER_TYPE_CHOICES,
            'symbol_types': Symbol.TYPE_CHOICES,
        }

        return context


class AlertListView(BaseAlertView):
    template_name = "alert/list.html"


class AlertView(BaseAlertView):
    template_name = "alert/form.html"

    def get_context_data(self, **kwargs):
        context = super(AlertView, self).get_context_data(**kwargs)
        alert_id = kwargs.get('pk', None)

        if alert_id:
            context['alert_id'] = alert_id
            context['action_url'] = reverse('api:alert-detail', kwargs={'user_pk': self.request.user.pk, 'pk': alert_id})
            context['method'] = 'PUT'

        else:
            context['action_url'] = reverse('api:alert-list', kwargs={'user_pk': self.request.user.pk})
            context['method'] = 'POST'

        context['coin_choices'] = [(symbol.id, symbol.name) for symbol in Symbol.objects.coins()]
        context['currency_choices'] = [(symbol.id, symbol.name) for symbol in Symbol.objects.currencies()]

        return context

pycoins/views/generic.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class RestrictedTemplateView(LoginRequiredMixin, TemplateView):
    redirect_field_name = 'next'

pycoins/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="PyCoins">

    <title>PyCoins</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment-with-locales.min.js"></script>
</head>

<body role="document">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        {% if user and user.is_authenticated %}
                            {{ user.username }}
                        {% else %}
                            Authenticate
                        {% endif %} <span class="caret"></span></a>

                    <ul class="dropdown-menu" role="menu">
                        {% if user and user.is_authenticated %}
                            <li><a href="{% url 'user-alerts' %}">My alerts</a></li>
                            <li><a href="{% url 'user-details' %}">My account</a></li>
                            {% if user.is_staff %}
                                <li><a href="{% url 'api:user-list' %}">All users</a></li>
                                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                            {% endif %}
                            <li class="divider"></li>
                            <li>
                                <a class="ajax-link" href="{% url 'api:rest_logout' %}" data-method="POST"
                                   data-redirect-to="{% url 'home' %}" data-success-event="logout-success">Logout</a>
                            </li>
                        {% else %}
                            <li><a href="{% url 'login' %}">Login</a></li>
                            <li><a href="{% url 'signup' %}">Signup</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">PyCoins</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a target="_blank" href="https://github.com/thomas-mckay/test-pycoins">Source code</a></li>
                    <li><a target="_blank" href="{% url 'api_docs' %}">API Docs</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>


    <div class="container theme-showcase" role="main">
        {% block content %}{% endblock %}
    </div>

    <div class="footer navbar-fixed-bottom" style="background-color: #eee">
        <p class="pull-right" style="margin: 5px 15px 5px 0">
            <small class="text-muted">
                <i>Designed like it's 1999</i>
            </small>
        </p>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        var sendAjax = function (url, method, data, successEvent, failEvent, redirectUrl) {
            var jwt = localStorage.getItem('jwt');

            return $.ajax({
                url: url,
                data: data,
                type: method,
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('Authorization', 'Token ' + jwt);
                    xhr.setRequestHeader('X-CSRFToken', "{{ csrf_token }}");
                }
            })

            .fail(function (data) {
                if (failEvent) {
                    $(document).trigger(failEvent, [data]);
                }
            })

            .done(function (data) {
                if (successEvent) {
                    $(document).trigger(successEvent, [data]);
                }

                if (redirectUrl) {
                    window.location.href = redirectUrl;
                }
            });
        };

        $(document).ready(function () {
            $(document).on('login-success', function(event, data) {
                localStorage.setItem('jwt', data['token']);
            });

            $(document).on('logout-success', function(event, data) {
                localStorage.removeItem('jwt');
            });

            $('form.ajax-form button[type=submit]').click(function (e) {
                e.preventDefault();

                var form = $(this).closest('form.ajax-form');

                sendAjax(
                    form.attr('action'),
                    form.data('method') || "POST",
                    form.serialize(),
                    form.data("success-event"),
                    form.data("fail-event"),
                    form.data("redirect-to"),

                ).done(function (data) {
                    form.find('.api-response').html("API Response: OK");

                }).fail(function (data) {
                    form.find('.api-response').html("API Response: " + data.status + ' ' + data.statusText + '<br/>Content: ' + data.responseText);
                })
            });

            $('a.ajax-link').click(function (e) {
                e.preventDefault();

                var link = $(this);

                sendAjax(
                    link.attr('href'),
                    link.data('method') || "GET",
                    {},
                    link.data("success-event"),
                    link.data("fail-event"),
                    link.data("redirect-to"),
                )
            });

            var ajaxList = $('.ajax-list');

            if (ajaxList.length > 0) {
                sendAjax(
                    ajaxList.data('url'),
                    ajaxList.data('method') || "GET",
                    {},
                    ajaxList.data("success-event"),
                    ajaxList.data("fail-event"),
                    ajaxList.data("redirect-to"),
                )
            }
        });
    </script>
    {% block script %}{% endblock %}
</body>
</html>

pycoins/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>PyCoins</h1>
        <p>Get alerts on your coin's exchange rates!</p>

        {% if user and user.is_authenticated %}
            <a class="btn btn-primary btn-lg" href="{% url 'user-alert-create' %}">Create an alert</a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            <span>&nbsp;or&nbsp;</span>
            <a class="btn btn-primary" href="{% url 'signup' %}">Create an account</a>
        {% endif %}
    </div>
{% endblock %}